//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacomberMapIntegratedService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8889")]
        public int TCPListener {
            get {
                return ((int)(this["TCPListener"]));
            }
            set {
                this["TCPListener"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\..\\Examples\\OneLines")]
        public string OneLineDirectory {
            get {
                return ((string)(this["OneLineDirectory"]));
            }
            set {
                this["OneLineDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\..\\Examples\\SystemFiles")]
        public string SystemFileDirectory {
            get {
                return ((string)(this["SystemFileDirectory"]));
            }
            set {
                this["SystemFileDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DatabaseEncryptedPassword {
            get {
                return ((string)(this["DatabaseEncryptedPassword"]));
            }
            set {
                this["DatabaseEncryptedPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DataSource=..\\..\\..\\..\\..\\Examples\\SystemFiles\\MacomberMapDatabase.sqlite")]
        public string DatabaseConnectionString {
            get {
                return ((string)(this["DatabaseConnectionString"]));
            }
            set {
                this["DatabaseConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HistoryServer {
            get {
                return ((string)(this["HistoryServer"]));
            }
            set {
                this["HistoryServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\..\\Examples\\OperatorCommandsToCoreSystem")]
        public string OperatorCommandPath {
            get {
                return ((string)(this["OperatorCommandPath"]));
            }
            set {
                this["OperatorCommandPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\..\\Examples\\LoginOperatorships.csv")]
        public string LoginFileLocation {
            get {
                return ((string)(this["LoginFileLocation"]));
            }
            set {
                this["LoginFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net.tcp://localhost:8774/MacomberMapAdministratorInterface.svc,http://localhost:8" +
            "733/Design_Time_Addresses/MacomberMapServer/MacomberMapAdministratorInterface")]
        public string MacomberMapAdministratorAddress {
            get {
                return ((string)(this["MacomberMapAdministratorAddress"]));
            }
            set {
                this["MacomberMapAdministratorAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net.tcp://localhost:8774/MacomberMapWCFService.svc,http://localhost:8733/Design_T" +
            "ime_Addresses/MacomberMapServer/MacomberMapWCFService/")]
        public string MacomberMapServerAddress {
            get {
                return ((string)(this["MacomberMapServerAddress"]));
            }
            set {
                this["MacomberMapServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56575")]
        public int MacomberMapServerQueryPort {
            get {
                return ((int)(this["MacomberMapServerQueryPort"]));
            }
            set {
                this["MacomberMapServerQueryPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56574")]
        public int MacomberMapServerBroadcastPort {
            get {
                return ((int)(this["MacomberMapServerBroadcastPort"]));
            }
            set {
                this["MacomberMapServerBroadcastPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string OperatorCommandTCPAddress {
            get {
                return ((string)(this["OperatorCommandTCPAddress"]));
            }
            set {
                this["OperatorCommandTCPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9000")]
        public int OperatorCommandTCPPort {
            get {
                return ((int)(this["OperatorCommandTCPPort"]));
            }
            set {
                this["OperatorCommandTCPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\..\\Examples\\RealTime Data")]
        public string TEDESourceFolder {
            get {
                return ((string)(this["TEDESourceFolder"]));
            }
            set {
                this["TEDESourceFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowTestCredentials {
            get {
                return ((bool)(this["AllowTestCredentials"]));
            }
            set {
                this["AllowTestCredentials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Development system")]
        public string MacomberMapServerDescription {
            get {
                return ((string)(this["MacomberMapServerDescription"]));
            }
            set {
                this["MacomberMapServerDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForwardCommandsToERCOTClients {
            get {
                return ((bool)(this["ForwardCommandsToERCOTClients"]));
            }
            set {
                this["ForwardCommandsToERCOTClients"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForwardCommandsToAdminClients {
            get {
                return ((bool)(this["ForwardCommandsToAdminClients"]));
            }
            set {
                this["ForwardCommandsToAdminClients"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\..\\Examples\\OperatorCommandLog")]
        public string CommandFileLocation {
            get {
                return ((string)(this["CommandFileLocation"]));
            }
            set {
                this["CommandFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\..\\Examples\\MacomberMapServerLog.html")]
        public string LogFileLocation {
            get {
                return ((string)(this["LogFileLocation"]));
            }
            set {
                this["LogFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AcceptAllDomainUsers {
            get {
                return ((bool)(this["AcceptAllDomainUsers"]));
            }
            set {
                this["AcceptAllDomainUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System.Data.SQLite.SQLiteConnection")]
        public string DatabaseConnectionType {
            get {
                return ((string)(this["DatabaseConnectionType"]));
            }
            set {
                this["DatabaseConnectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO MM_NOTE (ID, CreatedOn, Author, Note, AssociatedElement, Acknowledged" +
            ") VALUES (SEQ_MM_NOTE.NEXTVAL, :CreatedOn, :Author, :Note, :AssociatedElement, :" +
            "Acknowledged) RETURNING ID into :ID")]
        public string DatabaseNoteInsertCommand {
            get {
                return ((string)(this["DatabaseNoteInsertCommand"]));
            }
            set {
                this["DatabaseNoteInsertCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE MM_Training_Session SET {Title}=:Title, LastUpdate=:LastUpdate WHERE Id=:I" +
            "d")]
        public string DatabaseTrainingUpdateCommand {
            get {
                return ((string)(this["DatabaseTrainingUpdateCommand"]));
            }
            set {
                this["DatabaseTrainingUpdateCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System.Data.SQLite")]
        public string DatabaseAssembly {
            get {
                return ((string)(this["DatabaseAssembly"]));
            }
            set {
                this["DatabaseAssembly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO MM_Training_Session (UserName, StartTime, PriorLevel,Score,SystemName" +
            ") VALUES (:UserName,:CurrentDate, 0, 0,:MachineName); SELECT last_insert_rowid()" +
            ";")]
        public string DatabaseTrainingStartCommand {
            get {
                return ((string)(this["DatabaseTrainingStartCommand"]));
            }
            set {
                this["DatabaseTrainingStartCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\..\\Examples\\TrainingLeaderboard.html")]
        public string TrainingGameHtmlFile {
            get {
                return ((string)(this["TrainingGameHtmlFile"]));
            }
            set {
                this["TrainingGameHtmlFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM MM_Training_Session;")]
        public string TrainingGameQuery {
            get {
                return ((string)(this["TrainingGameQuery"]));
            }
            set {
                this["TrainingGameQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<tr><td>{UserName}</td><td>{Score:#,##0}</td><td>{CurrentLevel}</td></tr>")]
        public string TrainingGameOutputLine {
            get {
                return ((string)(this["TrainingGameOutputLine"]));
            }
            set {
                this["TrainingGameOutputLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\..\\Examples\\SystemFiles\\MacomberMap-Combined.MM_Model")]
        public string ModelFilePath {
            get {
                return ((string)(this["ModelFilePath"]));
            }
            set {
                this["ModelFilePath"] = value;
            }
        }
    }
}
